# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYGL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeviceManage
pod 'AFNetworking' , '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'SDCycleScrollView', '~> 1.73'
pod 'SDAutoLayout'
pod 'MJRefresh'
pod 'DOPDropDownMenu-Enhanced'
pod 'JPush'
pod 'AMapLocation'
pod 'Masonry'
pod 'LANCategory'
pod 'pop'
pod 'YYModel'
pod 'YYCategories'
end
